enum Options {SEARCH,TRACK};
enum Priority {LOW, MEDUIM, HIGH};

struct SearchType{
	float lat;
	float lon;	
	short alt;
};

struct TrackType{
	long trackID;
	Priority priority;
};

union radarUnion
	switch (Options){ 
		case SEARCH: 
			SearchType searchInfo; 
		case TRACK:
			TrackType trackInfo;
};

struct TimeStampStruct{
	short milisec;
	short sec;
	short minutes;
	short hour;
	short day;
	short month;
	short year;
};

struct RadarCommand{
	TimeStampStruct timeStamp;
	long sequenceNumber;
	radarUnion radarInfo;
};


